#!/usr/bin/env zsh

source $ZDOTDIR/zsh-functions

case $(hostname -s) in
  "penguin-traveler")
    pathremove $HOME/bin
    pathadd $TEXLIVE/bin/x86_64-linux before
    #pathadd $GNATHOME/gnatstudio/bin before
    pathadd $QTHOME/bin before
    pathadd $PGHOME/bin before
    pathadd $GOROOT/bin before
    pathadd $GOPATH/bin before
    pathadd $HOME/.cargo/bin before
    pathadd $NPM_PACKAGES/bin before
    pathadd $HOME/.emacs.d/bin before
    pathadd $HOME/.local/bin before
    pathadd $HOME/bin before

    [ -f "/home/tony/.ghcup/env" ] && source "/home/tony/.ghcup/env" # ghcup-env
    ;;
  "tony-mbp")
    pathadd "/opt/X11/bin"
    pathadd "/Library/TeX/textbin"
    pathadd "$HOME/usr/local/go/bin"
    pathadd "$HOME/.opam/default/bin"
    pathadd "$HOME/tony/opt/condabin"
    pathadd "$HOME/opt/anaconda3/bin"
    pathadd "$HOME/.ghcup/bin"
    pathadd "$HOME/tony/.cabal/bin:"
    pathadd "$HOME/.cargo/bin"
    pathadd "$HOME/.emacs.d/bin"
    pathadd "$HOME/.local/bin"
    pathadd "$HOME/bin"
    ;;
  *) 
    export PATH="$HOME/.local/bin:$PATH"
    export PATH="$HOME/.emacs.d/bin:$PATH"
    export PATH="$HOME/bin:$PATH"
    ;;
esac
  
