#!/usr/bin/env zsh

source $ZDOTDIR/zsh-functions

case $(hostname -s) in
  "penguin-traveler")
    pathremove $HOME/bin
    pathadd $TEXLIVE/bin/x86_64-linux before
    #pathadd $GNATHOME/gnatstudio/bin before
    pathadd $QTHOME/bin before
    pathadd $PGHOME/bin before
    pathadd $GOROOT/bin before
    pathadd $GOPATH/bin before
    pathadd $HOME/.cargo/bin before
    pathadd $NPM_PACKAGES/bin before
    pathadd $HOME/.emacs.d/bin before
    pathadd $HOME/.local/bin before
    pathadd $HOME/bin before

    [ -f "/home/tony/.ghcup/env" ] && source "/home/tony/.ghcup/env" # ghcup-env
    ;;
  "tony-mbp")
    #echo "--->PATH=$PATH" | tr ':' '\n'
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"  
    pathadd $GOROOT/bin
    pathadd "/opt/X11/bin"
    pathadd "/Library/TeX/textbin"
    #pathadd "$HOME/.opam/default/bin"
    #pathadd "$HOME/opt/anaconda3/bin"
    #pathadd "$HOME/opt/condabin"
    pathadd "$HOME/.ghcup/bin"
    pathadd "$HOME/.cabal/bin"
    pathadd "$HOME/.cargo/bin"
    pathadd "$HOME/.emacs.d/bin"
    pathadd "$HOME/.local/bin"
    pathadd "$HOME/bin"
    pathadd "$HOME/.config/local/share/nvim/site/pack/packer/start/fzf/bin" after
    ;;
  *) 
    export PATH="$HOME/.local/bin:$PATH"
    export PATH="$HOME/.emacs.d/bin:$PATH"
    export PATH="$HOME/bin:$PATH"
    ;;
esac
  
